backend/models/Product.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "product".
 *
 * @property int $id
 * @property int $category_id
 * @property string $title
 * @property string $content
 * @property float $price
 * @property float $old_price
 * @property string|null $description
 * @property string|null $keywords
 * @property string $img
 * @property int $is_offer
 */
class Product extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'product';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['category_id', 'title', 'content'], 'required'],
            [['category_id', 'is_offer'], 'integer'],
            [['content'], 'string'],
            [['price', 'old_price'], 'number'],
            [['title', 'description', 'keywords', 'img'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category_id' => 'Category ID',
            'title' => 'Title',
            'content' => 'Content',
            'price' => 'Price',
            'old_price' => 'Old Price',
            'description' => 'Description',
            'keywords' => 'Keywords',
            'img' => 'Img',
            'is_offer' => 'Is Offer',
        ];
    }
}

frontend/models/Product.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "product".
 *
 * @property int $id
 * @property int $category_id
 * @property string $title
 * @property string $content
 * @property float $price
 * @property float $old_price
 * @property string|null $description
 * @property string|null $keywords
 * @property string $img
 * @property int $is_offer
 */
class Product extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'product';
    }

    public function getCategory()
    {
        return $this->hasOne(Category::class, ['id' => 'category_id']);
    }
    

}

frontend/controllers/CartController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Cart;
use frontend\models\Order;
use frontend\models\Product;
use frontend\models\UserCart;
use frontend\models\OrderProduct;
use yii\web\NotFoundHttpException;

class CartController extends AppController
{

    public function actionAdd($id, $qty = 1)
    {
        if(Yii::$app->request->isPost) {
            $qty = Yii::$app->request->post('quantity');
        }
        $product = Product::findOne($id);
        if(empty($product)) {
            throw new NotFoundHttpException('Такого продукта нет');
        }
        if(Yii::$app->user->isGuest) {
            Cart::addProduct($product, $qty);
        } else {
            UserCart::addProduct($product, $qty);
        }
        if(Yii::$app->request->isAjax) {
            return;
        }
        return $this->redirect(Yii::$app->request->referrer ?: Yii::$app->homeUrl);
    }
    
    public function actionCheckout()
    {
        $this->setMeta('Оформление заказа', 'заказ, оформление заказа', 'оформление заказа');
        $order = new Order();
        $orderProducts = new OrderProduct();
        $transaction = Yii::$app->getDb()->beginTransaction();
        if(Yii::$app->user->isGuest) {
            $session = Yii::$app->session;
            if($order->load(Yii::$app->request->post())) {
                $order->qty = $session['qty'];
                $order->total = $session['sum'];
                if(!$order->save() || !$orderProducts->saveSessProducts($session['cart'], $order->id)) {
                    $transaction->rollBack();
                    Yii::$app->session->setFlash('error', 'Ошибка при оформлении заказа!');
                    return $this->refresh();
                } else {
                    $transaction->commit();
//                    Yii::$app->mailer->compose()
//                        ->setFrom([Yii::$app->params['senderEmail'] => Yii::$app->params['senderName']])
//                        ->setTo($order->email)
//                        ->setSubject('Новый заказ')
//                        ->send();
                    Cart::clear($session);
                    Yii::$app->session->setFlash('success', 'Ваш заказ успешно принят!');
                    return $this->refresh();
                }
            }
            return $this->render('checkout', compact('session', 'order'));
        }
        $model = UserCart::getUserCart();
        if($order->load(Yii::$app->request->post())) {
            $order->user_id = Yii::$app->user->identity->id;
            $order->qty = UserCart::getQty();
            $order->total = UserCart::getSum();
            if(!$order->save() | !$orderProducts->saveProducts($model, $order->id)) {
                $transaction->rollBack();
                Yii::$app->session->setFlash('error', 'Ошибка при оформлении заказа!');
                return $this->refresh();
            } else {
                $transaction->commit();
//                Yii::$app->mailer->compose()
//                    ->setFrom([Yii::$app->params['senderEmail'] => Yii::$app->params['senderName']])
//                    ->setTo($order->email)
//                    ->setSubject('Новый заказ')
//                    ->setTextBody($model)
//                    ->send();
                UserCart::clear();
                Yii::$app->session->setFlash('success', 'Ваш заказ успешно принят!');
                return $this->refresh();
            }
        }
        return $this->render('userCheckout', [
            'model' => $model,
            'order' => $order
        ]);
    }
    
    public function actionChange()
    {
        $id = Yii::$app->request->get('id');
        $qty = Yii::$app->request->get('qty');
        $product = Product::findOne($id);
        
        if(empty($product)) {
            throw new NotFoundHttpException('Такого продукта нет');
        }
        if(Yii::$app->user->isGuest) {
            Cart::addProduct($product, $qty);
            return true;
        } else {
            UserCart::addProduct($product, $qty);
            return true;
        }
        return false;
    }

    public function actionView()
    {
        if(Yii::$app->user->isGuest) {
//            $session = Yii::$app->session;
//            $session->open();
            return $this->render('cartView', [
                //'model' => $session
            ]);
        } else {
            $model = UserCart::getUserCart();
            $qty = 0;
            $sum = 0;
            foreach ($model as $product) {
                $qty += $product->qty;
                $sum += $product->sum;
            }
            if(isset($_POST['del_all'])) {
                foreach ($model as $product) {
                    $this->actionDelete($product->id);
                }
            }
            return $this->render('usercartView', [
                'model' => $model,
                'qty' => $qty,
                'sum' => $sum,
            ]);
        }
    }

    public function actionDelete($id)
    {
        if(Yii::$app->user->isGuest) {
            unset($_SESSION['cart'][$id]);
            return $this->redirect(Yii::$app->request->referrer);
        } else {
            $product = UserCart::findOne($id);
            $product->delete();
            return $this->redirect(Yii::$app->request->referrer);
        }
    }
    
    public function actionDeleteall()
    {
        if(Yii::$app->user->isGuest) {
            unset($_SESSION['cart']);
            unset($_SESSION['qty']);
            unset($_SESSION['sum']);
            return $this->redirect(Yii::$app->request->referrer);
        } else {
            $model = UserCart::getUserCart();
            foreach($model as $product) {
                $this->actionDelete($product->id);
            }
            return $this->redirect(Yii::$app->request->referrer);
        }
    }

}

frontend/controllers/ProductController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Product;
use frontend\models\Category;
use yii\data\Pagination;
use yii\web\NotFoundHttpException;

class ProductController extends AppController
{
    public function actionSearch()
    {
        $q = trim(Yii::$app->request->get('q'));
        $this->setMeta('Поиск: ' . $q);

        if(!$q) {
            return $this->render('search');
        }

        $query = Product::find()->where(['like', 'title', $q]);
        //debug($query->count());exit;

        $pages = new Pagination(['totalCount' => $query->count(), 
        'pageSize' => 2, 'forcePageParam' => false, 'pageSizeParam' => false]);
        
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();
        
        return $this->render('search', [
            'products' => $products,
            'pages' => $pages,
            'q' => $q
        ]);
    }

    public function actionView($id)
    {
        $product = Product::findOne($id);
        if(empty($product)) {
            throw new NotFoundHttpException('Запрошенного продукта не существует');
        }

        $this->setMeta("$product->title", $product->keywords, $product->description);

        $categoryOfProduct = Category::find()->where(['id' => $product->category_id])->one();
        $products = Product::find()->where(['category_id' => $categoryOfProduct->id])->all();

        return $this->render('view', [
            'product' => $product,
            'products' => $products,
            'category' => $categoryOfProduct
        ]);
    }

}

frontend/views/product/search.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Url;
?>

<div class="banner">
<?= $this->render('//layouts/inc/sidebar.php') ?>
    <div class="w3l_banner_nav_right">
        <section class="slider">
            <div class="flexslider">
                <ul class="slides">
                    <li>
                        <div class="w3l_banner_nav_right_banner">
                            <h3>Make your <span>food</span> with Spicy.</h3>
                            <div class="more">
                                <a href="products.html" class="button--saqui button--round-l button--text-thick" data-text="Shop now">Shop now</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="w3l_banner_nav_right_banner1">
                            <h3>Make your <span>food</span> with Spicy.</h3>
                            <div class="more">
                                <a href="products.html" class="button--saqui button--round-l button--text-thick" data-text="Shop now">Shop now</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="w3l_banner_nav_right_banner2">
                            <h3>upto <i>50%</i> off.</h3>
                            <div class="more">
                                <a href="products.html" class="button--saqui button--round-l button--text-thick" data-text="Shop now">Shop now</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </section>
    </div>
    <div class="clearfix"></div>
</div>

<div class="w3ls_w3l_banner_nav_right_grid">
            <h3><?= "Результаты поиска по запросу: " . $q ?></h3>
            <?php if(!empty($products)): ?>
            <div class="w3ls_w3l_banner_nav_right_grid1">
                <?php foreach($products as $product): ?>
                <div class="col-md-3 w3ls_w3l_banner_left">
                    <div class="hover14 column">
                        <div class="agile_top_brand_left_grid w3l_agile_top_brand_left_grid">
                            <?php if($product->is_offer): ?>
                            <div class="agile_top_brand_left_grid_pos">
                                <?= \yii\helpers\Html::img('@web/images/offer.png', ['alt' => 'offer', 'class' => 'img-responsive']) ?>
                            </div>
                            <?php endif; ?>
                            <div class="agile_top_brand_left_grid1">
                                <figure>
                                    <div class="snipcart-item block">
                                        <div class="snipcart-thumb">
                                            <a href="<?= \yii\helpers\Url::to(['product/view', 'id' => $product->id]) ?>">
                                                <?= \yii\helpers\Html::img("@web/products/{$product->img}", ['alt' => $product->title]) ?>
                                            </a>
                                            <p><?= $product->title ?></p>
                                            <h4>
                                                $<?= $product->price ?>
                                                <?php if((float)$product->old_price): ?>
                                                    <span>$<?= $product->old_price ?></span>
                                                <?php endif; ?>
                                            </h4>
                                        </div>
                                        <form method="post" action="<?= Url::to(['cart/add', 'id' => $product->id])?>">
                                        <div class="snipcart-details">
                                            <input type="number" class="input-qty" name="quantity" min="1" max="10" value="1">
                                            <input type="submit" name="submit" class="add-to-cart" data-id="<?= $product->id ?>">
                                        </div>
                                    </form>
                                    </div>
                                </figure>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
                <div class="clearfix"> </div>
								<div class="col-md-12">
								    <?= yii\widgets\LinkPager::widget([
											'pagination' => $pages,
										])?>
								</div>
            </div>
            <?php else: ?>
                <div class="w3ls_w3l_banner_nav_right_grid1">
                    <h6>По вашему запросу не было найдено ни одного товара...</h6>
                </div>
            <?php endif; ?>
        </div>

frontend/views/product/view.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Url;

?>

<!-- products-breadcrumb -->
	<div class="products-breadcrumb">
		<div class="container">
			<ul>
				<li><i class="fa fa-home" aria-hidden="true"></i><a href="<?= Url::to(['/home']) ?>">Home</a><span>|</span></li>
				<li><?= $product->category->title . ' | ' . $product->title ?></li>
			</ul>
		</div>
	</div>
<!-- //products-breadcrumb -->
<!-- banner -->
	<div class="banner">
		<?= $this->render('//layouts/inc/sidebar.php') ?>
		<div class="w3l_banner_nav_right">
			<div class="w3l_banner_nav_right_banner3">
				<h3>Best Deals For New Products<span class="blink_me"></span></h3>
			</div>
			<div class="agileinfo_single">
                <h5><?= $product->title ?></h5>
                
				<div class="col-md-4 agileinfo_single_left">
                <?php if($product->is_offer): ?>
                    <div class="agile_top_brand_left_grid_pos">
                        <?= \yii\helpers\Html::img('@web/images/offer.png', ['alt' => 'offer', 'class' => 'img-responsive']) ?>
                    </div>
                <?php endif; ?>
                    <!-- <img id="example" src="images/76.png" alt=" " class="img-responsive" /> -->
										<?= \yii\helpers\Html::img("@web/images/{$product->img}", ['alt' => $product->title, 
										'id' => 'example']) ?>
				</div>
				<div class="col-md-8 agileinfo_single_right">
					<div class="rating1">
						<span class="starRating">
							<input id="rating5" type="radio" name="rating" value="5">
							<label for="rating5">5</label>
							<input id="rating4" type="radio" name="rating" value="4">
							<label for="rating4">4</label>
							<input id="rating3" type="radio" name="rating" value="3" checked>
							<label for="rating3">3</label>
							<input id="rating2" type="radio" name="rating" value="2">
							<label for="rating2">2</label>
							<input id="rating1" type="radio" name="rating" value="1">
							<label for="rating1">1</label>
						</span>
					</div>
					<div class="w3agile_description">
						<h4>Description :</h4>
						<p><?= $product->description ?></p>
					</div>
					<div class="snipcart-item block">
						<div class="snipcart-thumb agileinfo_single_right_snipcart">
                            <h4><?= $product->price ?>
                            <?php if((float)$product->old_price): ?><span><?= $product->old_price ?></span><?php endif; ?>
                        </h4>
						</div>

							<!-- <select id="k" class="qty">
								<option class="qty__item" value="1">1</option>
								<option class="qty__item" value="2">2</option>
								<option class="qty__item" value="3">3</option>
								<option class="qty__item" value="4">4</option>
								<option class="qty__item" value="5">5</option>
								<option class="qty__item" value="6">6</option>
								<option class="qty__item" value="7">7</option>
								<option class="qty__item" value="8">8</option>
								<option class="qty__item" value="9">9</option>
								<option class="qty__item" value="10">10</option>
							</select> -->
							<form method="post" action="<?= Url::to(['cart/add', 'id' => $product->id])?>">
								<div class="snipcart-details">
									<input type="number" class="input-qty" name="quantity" min="1" max="10" value="1">
									<input type="submit" name="submit" class="add-to-cart" data-id="<?= $product->id ?>">
								</div>
							</form>
						
						<!-- <div class="snipcart-details agileinfo_single_right_details">
							<form action="#" method="post">
								<fieldset>
									<input type="hidden" name="cmd" value="_cart" />
									<input type="hidden" name="add" value="1" />
									<input type="hidden" name="business" value=" " />
									<input type="hidden" name="item_name" value="pulao basmati rice" />
									<input type="hidden" name="amount" value="21.00" />
									<input type="hidden" name="discount_amount" value="1.00" />
									<input type="hidden" name="currency_code" value="USD" />
									<input type="hidden" name="return" value=" " />
									<input type="hidden" name="cancel_return" value=" " />
									<input type="submit" name="submit" value="Add to cart" class="button" />
								</fieldset>
							</form>
						</div> -->
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
<!-- //banner -->
<!-- brands -->
	<div class="w3ls_w3l_banner_nav_right_grid w3ls_w3l_banner_nav_right_grid_popular">
		<div class="container">
			<h3>Another products of this category</h3>
				<div class="w3ls_w3l_banner_nav_right_grid1">
                    <h6><?= $category->title ?></h6>
                    <?php foreach($products as $categoryProduct): ?>
					<div class="col-md-3 w3ls_w3l_banner_left">
						<div class="hover14 column">
						<div class="agile_top_brand_left_grid w3l_agile_top_brand_left_grid">
                        <?php if($categoryProduct->is_offer): ?>
                            <div class="agile_top_brand_left_grid_pos">
                                <?= \yii\helpers\Html::img('@web/images/offer.png', ['alt' => 'offer', 'class' => 'img-responsive']) ?>
                            </div>
                        <?php endif; ?>
							<div class="agile_top_brand_left_grid1">
								<figure>
									<div class="snipcart-item block">
										<div class="snipcart-thumb">
                                            <a href="<?= \yii\helpers\Url::to(['product/view', 'id' => $categoryProduct->id]) ?>">
                                            <?= \yii\helpers\Html::img(
                                                "@web/images/{$categoryProduct->img}", ['alt' => $categoryProduct->title, 
                                                'class' => 'img-responsive'
                                                ]
                                            ) ?>
                                        </a>
											<p><?= $categoryProduct->title ?></p>
                                            <h4><?= $categoryProduct->price ?>
                                             <?php if((float)$categoryProduct->old_price): ?><span>
                                                 <?= $categoryProduct->old_price ?>
                                            </span><?php endif; ?>
                                            </h4>
										</div>
										<a href="<?= Url::to(['cart/add', 'id' => $categoryProduct->id]) ?>" class="snipcart-details agileinfo_single_right_details">Add to cart</a>
									</div>
								</figure>
							</div>
						</div>
						</div>
                    </div>
                    <?php endforeach; ?>
					<div class="clearfix"> </div>
				</div>
		</div>
	</div>
<!-- //brands -->
<!-- newsletter -->
	<div class="newsletter">
		<div class="container">
			<div class="w3agile_newsletter_left">
				<h3>sign up for our newsletter</h3>
			</div>
			<div class="w3agile_newsletter_right">
				<form action="#" method="post">
					<input type="email" name="Email" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" required="">
					<input type="submit" value="subscribe now">
				</form>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
<!-- //newsletter -->