frontend/models/Cart.php
<?php

namespace frontend\models;

use Yii;
use yii\base\Model;
use frontend\models\interfaces\ICart;

/*
	'cart' => [
		'1' => [
			'title' => Title
			'price' => price
			'img' => img
			'qty' => 5
		],

		'2' => [
			'title' => Title2
			'price' => price2
			'img' => img2
			'qty' => 2
		],

		'3' => [
			'title' => Title3
			'price' => price23
			'img' => img3
			'qty' => 1
		]

	],
	'qty' => 10,
	'sum' => 48,
		
*/

class Cart extends Model implements ICart
{

	public static function addProduct($product, $qty = 1)
	{
		$session = Yii::$app->session;
		//$session->destroy();exit;
		$session->open();
		$qty = ($qty == '-1') ? -1 : 1;
                if(isset($_SESSION['cart'][$product->id])){
                    $_SESSION['cart'][$product->id]['qty'] += $qty;
                }else{
                    $_SESSION['cart'][$product->id] = [
                        'id' => $product->id,
                        'title' => $product->title,
                        'price' => $product->price,
                        'qty' => $qty,
                        'img' => $product->img,
                    ];
                }
                $_SESSION['qty'] = isset($_SESSION['qty']) ? $_SESSION['qty'] + $qty : $qty;
                $_SESSION['sum'] = isset($_SESSION['sum']) ? $_SESSION['sum'] + $qty * $product->price : $qty * $product->price;
                if($_SESSION['cart'][$product->id]['qty'] == 0){
                    unset($_SESSION['cart'][$product->id]);
                }
	}
        
        public static function clear($session)
        {
            $session->remove('cart');
            $session->remove('qty');
            $session->remove('sum');
        }

}

frontend/controllers/CartController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Cart;
use frontend\models\Order;
use frontend\models\Product;
use frontend\models\UserCart;
use frontend\models\OrderProduct;
use yii\web\NotFoundHttpException;

class CartController extends AppController
{

    public function actionAdd($id, $qty = 1)
    {
        if(Yii::$app->request->isPost) {
            $qty = Yii::$app->request->post('quantity');
        }
        $product = Product::findOne($id);
        if(empty($product)) {
            throw new NotFoundHttpException('Такого продукта нет');
        }
        if(Yii::$app->user->isGuest) {
            Cart::addProduct($product, $qty);
        } else {
            UserCart::addProduct($product, $qty);
        }
        if(Yii::$app->request->isAjax) {
            return;
        }
        return $this->redirect(Yii::$app->request->referrer ?: Yii::$app->homeUrl);
    }
    
    public function actionCheckout()
    {
        $this->setMeta('Оформление заказа', 'заказ, оформление заказа', 'оформление заказа');
        $order = new Order();
        $orderProducts = new OrderProduct();
        $transaction = Yii::$app->getDb()->beginTransaction();
        if(Yii::$app->user->isGuest) {
            $session = Yii::$app->session;
            if($order->load(Yii::$app->request->post())) {
                $order->qty = $session['qty'];
                $order->total = $session['sum'];
                if(!$order->save() || !$orderProducts->saveSessProducts($session['cart'], $order->id)) {
                    $transaction->rollBack();
                    Yii::$app->session->setFlash('error', 'Ошибка при оформлении заказа!');
                    return $this->refresh();
                } else {
                    $transaction->commit();
//                    Yii::$app->mailer->compose()
//                        ->setFrom([Yii::$app->params['senderEmail'] => Yii::$app->params['senderName']])
//                        ->setTo($order->email)
//                        ->setSubject('Новый заказ')
//                        ->send();
                    Cart::clear($session);
                    Yii::$app->session->setFlash('success', 'Ваш заказ успешно принят!');
                    return $this->refresh();
                }
            }
            return $this->render('checkout', compact('session', 'order'));
        }
        $model = UserCart::getUserCart();
        if($order->load(Yii::$app->request->post())) {
            $order->user_id = Yii::$app->user->identity->id;
            $order->qty = UserCart::getQty();
            $order->total = UserCart::getSum();
            if(!$order->save() | !$orderProducts->saveProducts($model, $order->id)) {
                $transaction->rollBack();
                Yii::$app->session->setFlash('error', 'Ошибка при оформлении заказа!');
                return $this->refresh();
            } else {
                $transaction->commit();
//                Yii::$app->mailer->compose()
//                    ->setFrom([Yii::$app->params['senderEmail'] => Yii::$app->params['senderName']])
//                    ->setTo($order->email)
//                    ->setSubject('Новый заказ')
//                    ->setTextBody($model)
//                    ->send();
                UserCart::clear();
                Yii::$app->session->setFlash('success', 'Ваш заказ успешно принят!');
                return $this->refresh();
            }
        }
        return $this->render('userCheckout', [
            'model' => $model,
            'order' => $order
        ]);
    }
    
    public function actionChange()
    {
        $id = Yii::$app->request->get('id');
        $qty = Yii::$app->request->get('qty');
        $product = Product::findOne($id);
        
        if(empty($product)) {
            throw new NotFoundHttpException('Такого продукта нет');
        }
        if(Yii::$app->user->isGuest) {
            Cart::addProduct($product, $qty);
            return true;
        } else {
            UserCart::addProduct($product, $qty);
            return true;
        }
        return false;
    }

    public function actionView()
    {
        if(Yii::$app->user->isGuest) {
//            $session = Yii::$app->session;
//            $session->open();
            return $this->render('cartView', [
                //'model' => $session
            ]);
        } else {
            $model = UserCart::getUserCart();
            $qty = 0;
            $sum = 0;
            foreach ($model as $product) {
                $qty += $product->qty;
                $sum += $product->sum;
            }
            if(isset($_POST['del_all'])) {
                foreach ($model as $product) {
                    $this->actionDelete($product->id);
                }
            }
            return $this->render('usercartView', [
                'model' => $model,
                'qty' => $qty,
                'sum' => $sum,
            ]);
        }
    }

    public function actionDelete($id)
    {
        if(Yii::$app->user->isGuest) {
            unset($_SESSION['cart'][$id]);
            return $this->redirect(Yii::$app->request->referrer);
        } else {
            $product = UserCart::findOne($id);
            $product->delete();
            return $this->redirect(Yii::$app->request->referrer);
        }
    }
    
    public function actionDeleteall()
    {
        if(Yii::$app->user->isGuest) {
            unset($_SESSION['cart']);
            unset($_SESSION['qty']);
            unset($_SESSION['sum']);
            return $this->redirect(Yii::$app->request->referrer);
        } else {
            $model = UserCart::getUserCart();
            foreach($model as $product) {
                $this->actionDelete($product->id);
            }
            return $this->redirect(Yii::$app->request->referrer);
        }
    }

}

frontend/views/cart/cartView.php
<?php
/* @var $this yii\web\View */
/* @var $model Yii::$app->session */

use yii\helpers\Html;
use yii\helpers\Url;
?>

<?php if(isset($_SESSION['cart'])): ?>
        <a href="<?= Url::to(['cart/deleteall']) ?>">Удалить все товары</a>
        <p><a style="margin-left: 1000px" href="<?= Url::to(['cart/checkout']) ?>" class="btn btn-primary">Оформить заказ ($<?= $_SESSION['sum']?>)</a></p>
        <p>Общее количество выбранных товаров: <?= $_SESSION['qty']?></p>
        <p>Общая сумма: $<?= $_SESSION['sum']?></p>
        <br><br>
	<?php foreach ($_SESSION['cart'] as $product): ?>
        
            <p>Название продукта: <?= $product['title']?></p>
            <p>кол-во продукта: <?= $product['qty']?></p>
            <p>Цена одного продукта: $<?= $product['price'] ?></p>
            <p>Цена всех продуктов: $<?php $sum = $product['qty'] * $product['price']; echo $sum ?></p>
            <p><a href="<?= Url::to(['product/view', 'id' => $product['id']]) ?>"><?= Html::img("@web/images/{$product['img']}", ['alt' => $product['title']]) ?></a></p>
            <p><a href="<?= Url::to(['cart/delete', 'id' => $product['id']]) ?>">Удалить товар</a></p>
            <hr>
	<?php endforeach; ?>
<?php else: ?>
            <p>Ваша корзина пуста. <a href="<?= Url::to(['/home']) ?>">Вернуться к покупкам.</a></p>
<?php endif; ?>

frontend/views/cart/checkout.php
<?php

use yii\helpers\Url;
use yii\widgets\ActiveForm;

if($order->hasErrors()) {
    debug($order->getErrors());
}

echo app\widgets\Alert::widget();
?>
<!-- products-breadcrumb -->
<div class="products-breadcrumb">
    <div class="container">
        <ul>
            <li><i class="fa fa-home" aria-hidden="true"></i><a href="<?= \yii\helpers\Url::home() ?>">Home</a><span>|</span></li>
            <li>Оформление заказа</li>
        </ul>
    </div>
</div>
<!-- //products-breadcrumb -->
<!-- banner -->
<div class="banner">
    <?= $this->render('//layouts/inc/sidebar') ?>

    <div class="w3l_banner_nav_right">
        <!-- about -->
        <div class="privacy about">
            <h3>Chec<span>kout</span></h3>
            <?php if(!empty($session['cart'])): ?>
            <div class="checkout-right">
                <h4>Your shopping cart contains: <span><?= $session['qty'] ?> Product(s)</span></h4>
                <div class="cart-table">
                    <div class="overlay">
                        <i class="fa fa-refresh fa-spin"></i>
                    </div>
                    <table class="timetable_sub">
                    <thead>
                    <tr>
                        <th>SL No.</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Product Name</th>
                        <th>Price</th>
                        <th>Remove</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 1; foreach($session['cart'] as $id => $item): ?>
                    <tr>
                        <td class="invert"><?= $i ?></td>
                        <td class="invert-image">
                            <a href="<?= \yii\helpers\Url::to(['product/view', 'id' => $id]) ?>">
                                <?= \yii\helpers\Html::img("@web/products/{$item['img']}", ['alt' => $item['title']]) ?>
                            </a>
                        </td>
                        <td class="invert">
                            <div class="quantity">
                                <div class="quantity-select">
                                    <div class="entry value-minus" data-id="<?= $id ?>" data-qty="-1">&nbsp;</div>
                                    <div class="entry value"><span><?= $item['qty'] ?></span></div>
                                    <div class="entry value-plus active" data-id="<?= $id ?>" data-qty="1">&nbsp;</div>
                                </div>
                            </div>
                        </td>
                        <td class="invert"><?= $item['title'] ?></td>
                        <td class="invert">$<?= $item['price'] ?></td>
                        <td class="invert">
                            <div class="rem">
                                <a class="close1" href="<?= \yii\helpers\Url::to(['cart/delete', 'id' => $id]) ?>"></a>
                            </div>

                        </td>
                    </tr>
                    <?php $i++; endforeach; ?>
                    </tbody></table>
                </div>
            </div>
            <div class="checkout-left">
                <div class="col-md-4 checkout-left-basket">
                    <h4>Continue to basket</h4>
                    <ul>
                        <?php foreach($session['cart'] as $item): ?>
                        <li><?= $item['title'] ?> <i>-</i> <span>$<?= $item['price'] * $item['qty'] ?> </span></li>
                        <?php endforeach; ?>
                        <li>Total <i>-</i> <span>$<?= $session['sum'] ?></span></li>
                    </ul>
                </div>
                
                
                <div class="col-md-8 address_form_agile">
                    <h4>Add a new Details</h4>
                    <?php $form = ActiveForm::begin() ?>
                    <?= $form->field($order, 'name') ?>
                    <?= $form->field($order, 'email') ?>
                    <?= $form->field($order, 'phone') ?>
                    <?= $form->field($order, 'address') ?>
                    <?= $form->field($order, 'note')->textarea(['rows' => 5]) ?>
                    <?= yii\helpers\Html::submitButton('Заказать', ['class' => 'submit check_out']) ?>
                    <?php ActiveForm::end() ?>
                    <div class="checkout-right-basket">
                        <a href="payment.html">Make a Payment <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></a>
                    </div>
                </div>
                

                <div class="clearfix"> </div>

            </div>
            <?php else: ?>
                <h3>Корзина пуста</h3>
            <?php endif; ?>
        </div>
        <!-- //about -->
    </div>
    <div class="clearfix"></div>
</div>
<!-- //banner -->

frontend/views/cart/userCheckout.php
<?php

use yii\widgets\ActiveForm;

if($order->hasErrors()) {
    debug($order->getErrors());
}

echo app\widgets\Alert::widget();
?>
<!-- products-breadcrumb -->
<div class="products-breadcrumb">
    <div class="container">
        <ul>
            <li><i class="fa fa-home" aria-hidden="true"></i><a href="<?= \yii\helpers\Url::home() ?>">Home</a><span>|</span></li>
            <li>Оформление заказа</li>
        </ul>
    </div>
</div>
<!-- //products-breadcrumb -->
<!-- banner -->
<div class="banner">
    <?= $this->render('//layouts/inc/sidebar') ?>

    <div class="w3l_banner_nav_right">
        <!-- about -->
        <div class="privacy about">
            <h3>Chec<span>kout</span></h3>
            <?php if(!empty($model)): ?>
            <div class="checkout-right">
                <h4>Your shopping cart contains: <span><?= frontend\models\UserCart::getQty() ?> Product(s)</span></h4>
                <div class="cart-table">
                    <div class="overlay">
                        <i class="fa fa-refresh fa-spin"></i>
                    </div>
                    <table class="timetable_sub">
                    <thead>
                    <tr>
                        <th>SL No.</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Product Name</th>
                        <th>Price</th>
                        <th>Remove</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 1; foreach($model as $id => $item): ?>
                    <tr>
                        <td class="invert"><?= $i ?></td>
                        <td class="invert-image">
                            <a href="<?= \yii\helpers\Url::to(['product/view', 'id' => $item->product['id']]) ?>">
                                <?= \yii\helpers\Html::img("@web/products/{$item['img']}", ['alt' => $item->product->title]) ?>
                            </a>
                        </td>
                        <td class="invert">
                            <div class="quantity">
                                <div class="quantity-select">
                                    <div class="entry value-minus" data-id="<?= $item->product['id'] ?>" data-qty="-1">&nbsp;</div>
                                    <div class="entry value"><span><?= $item['qty'] ?></span></div>
                                    <div class="entry value-plus active" data-id="<?= $item->product['id'] ?>" data-qty="1">&nbsp;</div>
                                </div>
                            </div>
                        </td>
                        <td class="invert"><?= $item->product->title ?></td>
                        <td class="invert">$<?= $item->product['price'] ?></td>
                        <td class="invert">
                            <div class="rem">
                                <a class="close1" href="<?= \yii\helpers\Url::to(['cart/delete', 'id' => $item['id']]) ?>"></a>
                            </div>

                        </td>
                    </tr>
                    <?php $i++; endforeach; ?>
                    </tbody></table>
                </div>
            </div>
            <div class="checkout-left">
                <div class="col-md-4 checkout-left-basket">
                    <h4>Continue to basket</h4>
                    <ul>
                        <?php foreach($model as $item): ?>
                        <li><?= $item->product['title'] ?> <i>-</i> <span>$<?= $item->sum ?> </span></li>
                        <?php endforeach; ?>
                        <li>Total <i>-</i> <span>$<?= frontend\models\UserCart::getSum() ?></span></li>
                    </ul>
                </div>
                <div class="col-md-8 address_form_agile">
                    <h4>Add a new Details</h4>
                    <?php $form = ActiveForm::begin() ?>
                    <?= $form->field($order, 'name') ?>
                    <?= $form->field($order, 'email') ?>
                    <?= $form->field($order, 'phone') ?>
                    <?= $form->field($order, 'address') ?>
                    <?= $form->field($order, 'note')->textarea(['rows' => 5]) ?>
                    <?= yii\helpers\Html::submitButton('Заказать', ['class' => 'submit check_out']) ?>
                    <?php ActiveForm::end() ?>
                    <div class="checkout-right-basket">
                        <a href="payment.html">Make a Payment <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></a>
                    </div>
                </div>

                <div class="clearfix"> </div>

            </div>
            <?php else: ?>
                <h3>Корзина пуста</h3>
            <?php endif; ?>
        </div>
        <!-- //about -->
    </div>
    <div class="clearfix"></div>
</div>
<!-- //banner -->

frontend/views/cart/usercartView.php
<?php
/* @var $this yii\web\View */
/* @var $model frontend\models\UserCart */
use yii\helpers\Url;
use yii\helpers\Html;
use frontend\models\UserCart;

//debug($model, 1);
?>
<?php if(isset($model) && !empty($model)): ?>
<p> 
    <a href="<?= Url::to(['/cart/deleteall']) ?>">
        Удалить все позиции.
    </a>
</p>
<p><a style="margin-left: 1000px" href="<?= Url::to(['cart/checkout']) ?>" class="btn btn-primary">Оформить заказ(<?php echo $qty ?>)</a></p>
<br>
<p>Общее кол-во товаров: <?php echo $qty ?>. Общая сумма: $<?php echo $sum ?></p>
<?php foreach($model as $product): ?>
<p>Кол-во товара: <?php echo $product->qty ?></p>
<p>название товара: <?php echo $product->product->title ?></p>
<p>сумма всего товара: <?php echo $product->sum ?>$</p>
<p>сумма одного товара: <?php echo $product->product->price ?>$</p>
<a href="<?= Url::to(['product/view', 'id' => $product->product->id]) ?>"><?= Html::img("@web/products/{$product->product->img}", ['alt' => $product->product->title]); ?></a>
 <p>
     <a href="<?= Url::to(['/cart/delete', 'id' => $product->id]) ?>">
         Удалить товар
     </a>
 </p>
 <hr>
<?php endforeach; ?>
<?php else: ?>
<p>У вас нет товаров в корзине. <a href="<?= Url::to(['/home']) ?>">Вернуться к покупкам.</a></p>
<?php endif; ?>